# Generated by Django 4.2.11 on 2024-03-18 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0003_alter_verificationtokens_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('description', models.CharField(max_length=255)),
                ('private', models.BooleanField(default=False)),
                ('followers_num', models.PositiveIntegerField(default=0)),
                ('members_num', models.PositiveIntegerField(default=0)),
                ('followers', models.ManyToManyField(related_name='list_followers', to='user_auth.userprofile')),
                ('list_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.userprofile')),
                ('members', models.ManyToManyField(related_name='list_members', to='user_auth.userprofile')),
            ],
        ),
    ]
