# Generated by Django 4.2.11 on 2024-03-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_verificationtokens_token'),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='list_followers', to='user_auth.userprofile'),
        ),
        migrations.AlterField(
            model_name='list',
            name='followers_num',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='list',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='list_members', to='user_auth.userprofile'),
        ),
        migrations.AlterField(
            model_name='list',
            name='members_num',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='list',
            name='private',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
