# Generated by Django 4.2.11 on 2024-03-14 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_verificationtokens_userprofile'),
        ('following', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows_followers', to='user_auth.userprofile'),
        ),
        migrations.AlterField(
            model_name='follows',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows_following', to='user_auth.userprofile'),
        ),
    ]
