# Generated by Django 4.2.11 on 2024-03-14 22:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_verificationtokens_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtokens',
            name='token',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
