# Generated by Django 4.2.11 on 2024-03-27 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_verificationtokens_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtokens',
            name='token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='verificationtokens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
