# Generated by Django 4.2.11 on 2024-03-27 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_verificationtokens_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtokens',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
