# Generated by Django 4.2.11 on 2024-03-16 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='relpies',
            new_name='replies',
        ),
    ]
