# Generated by Django 4.2.11 on 2024-03-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_verificationtokens_token'),
        ('tweets', '0005_tag_tweet_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='users_mentioned',
            field=models.ManyToManyField(blank=True, related_name='tweet_users_mentioned', to='user_auth.userprofile'),
        ),
    ]
